Doll plays, showing my drawings, dancing, 
I always had so much fun when they watched and praised me for what I did.
They always gave me attention and care in those moments. 
My emotions mattered… Not like-... 
… 
What’s the next task?